#!/bin/sh

# REQUIRE: NETWORKING

. /etc/rc.subr

name=%NAME
rcvar=${name}_enable

pidfile=/var/run/${name}.pid
command="/usr/sbin/daemon"
command_args="-c -r -f -S -P ${pidfile} -T ${name} /usr/bin/env /${name}/start.sh"

load_rc_config $name
run_rc_command "$1"