import { writeFileSync } from "fs";
import { ColumnType } from "../instrumentation";
import type { SchemaInfo } from "./builder";

function maythraTypeToTypeScript(type: ColumnType) {
  switch (type) {
    case "BOOLEAN":
      return "boolean";
    case "DATE":
      return "Date";
    case "INTEGER":
    case "FLOAT32":
    case "FLOAT64":
      return "number";
    case "TEXT":
      return "string";
    default:
      throw "Type not implemented: " + type;
  }
}

export function genDeclaration(schemaInfo: SchemaInfo) {
  let declarationFile = `
/**
 *  File auto-generated by Maythra-ORM.
 * 
 *  Contains type declarations for your database.
 */  
    `;

  schemaInfo.tables.forEach((tableSchema) => {
    let tableName = tableSchema.tableName;
    if (tableName.endsWith("s"))
      tableName = tableName.substring(0, tableName.length - 1);

    declarationFile += `
export type ${tableName[0].toUpperCase() + tableName.substring(1)} = {
    ${tableSchema.columns
      .map(
        (v) =>
          `${v.name}${v.nullable ? "?" : ""}: ${maythraTypeToTypeScript(
            v.type
          )},`
      )
      .join("\n\t")}
}    
`;
  });

  writeFileSync("./maythra-types.d.ts", declarationFile);
}
