
/**
 *  File auto-generated by Maythra-ORM.
 * 
 *  Contains type declarations for your database.
 */  
    
export type User = {
    id: number,
	banana: string,
	isMiyuki: boolean,
	realname?: string,
}    
